version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16.2
    env_file: ./infra/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: ./infra/.env
    depends_on:
      - db
    volumes:
      - media:/app/media
      - static:/backend_static

  gateway:
    build: ./infra/
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
