version: '3'

volumes:
  pg_data:

services:

  db:
    image: postgres:16-alpine
    env_file: ./infra/.env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s
    ports:
      - ${DOCKER_COMPOSER_PORT:-5432:5432}
