version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16.2
    env_file: ./infra/.env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

  backend:
    image: blakkheart/diary_backend
    env_file: ./infra/.env
    depends_on:
      db:
        condition: service_healthy
    command:
        ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi"]
    volumes:
      - media:/app/media
      - static:/backend_static

  nginx:
    image: blakkheart/diary_gateway
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
