version: '3'

volumes:
  pg_data:
  redis_data:
  redis_conf:
  static:
  media:
  logs:

services:

  db:
    image: postgres:16.2
    env_file: .env
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 3s

  redis:
    image: redis:alpine
    env_file: .env
    restart: always
    volumes:
      - redis_data:/root/redis
      - redis_conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    image: blakkheart/diary_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
        ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi"]
    volumes:
      - media:/app/media
      - static:/backend_static
      - logs:/logs

  celery-worker:
    image: blakkheart/diary_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A config worker -l info
    volumes:
      - media:/app/media
      - static:/backend_static
      - logs:/logs

  minio:
    image: minio/minio:latest
    hostname: running.myddns.me
    environment:
      - MINIO_SERVER_URL=https://running.myddns.me:9000
    volumes:
      - ./minio:/minio_files
      - /home/tssdr/diary-training/minio/certs/:/opt/minio/certs
    env_file: .env
    command: 'minio server --certs-dir /opt/minio/certs /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file: .env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --quiet --api s3v4 s3 https://running.myddns.me:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet s3/running-app;
      /usr/bin/mc anonymous set public s3/running-app;
      "

  nginx:
    image: blakkheart/diary_gateway
    depends_on:
      - backend
      - minio
      - celery-worker
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
