version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16.2
    env_file:
      - path: ./infra/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: blakkheart/diary_backend
    env_file:
      - path: ./infra/.env
    depends_on:
      - db
    volumes:
      - media:/app/media
      - static:/backend_static

  gateway:
    image: blakkheart/diary_gateway
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
