version: '3'


services:

  minio:
    image: minio/minio:latest
    # hostname: "minio"
    volumes:
      - ./minio:/minio_files
    env_file: ./infra/.env
    command: 'minio server /minio_files --console-address ":9001"'
    ports:
      - 9000:9000
      - 9001:9001

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file: ./infra/.env
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add --quiet --api s3v4 s3 http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb --quiet s3/running-app;
      /usr/bin/mc anonymous set public s3/running-app;
      "

  # nginx:
  #   build: ./infra/
  #   depends_on:
  #     - minio
  #   ports:
  #     - 9000:80
  #     - 9001:80
  #   volumes:
  #     - ./minio:/minio_files
