# Generated by Django 5.0.3 on 2024-03-05 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.ForeignKey(db_comment='История пользователя.', default=1, help_text='История пользователя.', on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='reward_points',
            field=models.PositiveSmallIntegerField(db_comment='Количество заморозок за достижение.', default=0, help_text='Количество заморозок за достижение.', verbose_name='Заморозка'),
        ),
    ]
