# Generated by Django 5.0.3 on 2024-03-11 14:08

from django.db import migrations


def create_phrases(apps, schema_editor):
    """Создание мотивационных фраз."""
    MotivationalPhrase = apps.get_model("running", "MotivationalPhrase")
    phrases = (
        MotivationalPhrase(
            text="День начинается с первого шага.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег не имеет скорости, бег – это движение вперёд.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Маленькие шаги ведут к большим изменениям.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твоё время быть собой.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ощути каждый шаг.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Помни, величие растет в тишине и покое.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Победа над собой – лучшая победа.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не сравнивай себя с другими, соревнуйся с собой.",
            rest=False,
        ),
        MotivationalPhrase(
            text="С каждым шагом ты приближаешься к цели.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это свобода, которую ты даришь себе.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Преодолей свой внутренний разговор.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждый шаг наполняет тебя энергией.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сегодня ты станешь сильнее.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждая тренировка будет лучше предыдущей.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Найди свой темп и наслаждайся бегом.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твои ограничения – только в твоей голове.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сила в терпении и постоянстве.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Каждая тренировка приближает тебя к мечте.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бегай с улыбкой.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это праздник, который ты устраиваешь себе.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не бойся задать себе темп.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это не спорт, это стиль жизни.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ты можешь больше, чем думаешь.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Помни, почему ты начал.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Каждый день – новая возможность.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег делает тебя сильнее не только физически.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твоя скорость не важна, важно движение.",
            rest=False,
        ),
        MotivationalPhrase(
            text="С каждым шагом ты ближе к цели.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это медитация в движении.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не жди идеальных условий, просто начни.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бегай, чтобы чувствовать жизнь.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ты рожден побеждать.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждая тренировка дарит тебе силу.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твоя личная история успеха.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это не про скорость, это про направление.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Отмечай каждую маленькую победу на своем пути.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Помни: после дождя всегда выходит солнце.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твои ноги могут больше, чем говорит твой разум.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сегодняшний труд – завтрашняя победа.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это путешествие к себе.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ставь цели, дерзай, достигай.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Каждый шаг вперед делает тебя сильнее.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твой личный праздник.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это свидание с самим собой.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждый день приносит новые достижения.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твоя возможность блеснуть.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Наслаждайся каждым моментом на тропе.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждая пробежка делает тебя счастливее.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждый шаг наполняет тебя энергией.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твой шанс выйти за рамки.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твой путь к успеху начинается с первого шага.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твоя история, пиши ее с каждым шагом.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждая пробежка приближает тебя к мечте.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не сомневайся в себе, ты сильнее, чем кажется.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть твой бег будет полон вдохновения.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это не финиш, это путь.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твоя сила – в твоей настойчивости.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не бойся начать. Бойся остановиться.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждый шаг будет наполнен радостью.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твое время. Используй его с умом.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сегодня – идеальный день, чтобы превзойти себя.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твой лимит – только небо.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бегай, чтобы жить. Живи, чтобы бегать.",
            rest=False,
        ),
        MotivationalPhrase(
            text="С каждым днем ты крепче, сильнее и быстрее.",
            rest=False,
        ),
        MotivationalPhrase(
            text="В каждом из нас есть сила преодолевать.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это твой шанс каждый день становиться лучше.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть каждая пробежка наполняет тебя энергией и силой.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег – это не про скорость, это про направление.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сегодня ты бежишь к лучшей версии себя.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не давай себе отступить сегодня - победи свои границы.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Тренируй свою силу, упорство и выносливость.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Беги быстрее, чем твои оправдания.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Каждый беговой шаг приближает тебя к цели.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ты не останавливаешься - ты продолжаешь преодолевать себя.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сделай свои мечты реальностью - беги за ними.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег - это твой путь к здоровью и силе.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сегодняшний пот будет завтрашним успехом.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ты можешь больше, чем думаешь - продолжай бежать.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не ищи оправданий, ищи результаты.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ты сильнее, чем сомнения в твоей голове.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бегай с улыбкой - каждый шаг делает тебя сильнее.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твоя упорная работа приведет к блестящим результатам.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не останавливайся - сделай бег частью своей жизни.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Сегодняшний труд принесет завтрашние победы.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Беги с целью - достигни своей мечты.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Верь в себя, как веришь в следующий беговой шаг.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ты рожден для того, чтобы преодолевать препятствия.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ничто не остановит тебя, если ты не остановишься.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Пусть твои ноги несут тебя к новым высотам.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Ты не бежишь просто так - ты бежишь ради своей лучшей жизни.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не думай о том, сколько осталось - просто беги сегодня.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Беги с уверенностью - ты на верном пути.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Каждый шаг делает тебя сильнее, чем ты был вчера.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Подними стандарты - бегай сильнее, дольше, быстрее.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Не забывай, что даже самый медленный прогресс все равно прогресс.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бегай так, будто твоя жизнь зависит от этого - потому что она и правда зависит.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твоя решимость преодолеть усталость сделает тебя победителем.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Бег - это не только физическая тренировка, но и испытание духа.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Твой внутренний голос говорит 'остановись', но ты знаешь, что можешь сделать больше.",
            rest=False,
        ),
        MotivationalPhrase(
            text="С каждым днем ты становишься ближе к своей лучшей версии - не останавливайся.",
            rest=False,
        ),
        MotivationalPhrase(
            text="Отдых – это не лень, это инвестиция в твою следующую победу.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Восстановление – ключ к росту. Дай своему телу то, что ему нужно.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдыхай, когда устал, но не сдавайся.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдыхая, ты заряжаешься силой для новых свершений.",
            rest=True,
        ),
        MotivationalPhrase(
            text="В каждом отдыхе – залог новых достижений.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Сила в балансе между нагрузкой и восстановлением.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Твой путь – твои правила, отдохни.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это когда ты растешь.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Сегодня отдых, чтобы завтра бежать быстрее.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Позволь себе быть несовершенным.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Пусть твой отдых будет так же продуктивен, как и тренировка.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Твое тело знает, что ему нужен отдых. Слушай его.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это часть твоего пути к успеху.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Время восстановления – это время, когда чудеса становятся возможными.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это не просто перерыв, это стратегия достижения целей.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это часть тренировки.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Дай себе разрешение на отдых. Ты этого заслужил.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Восстановление – это когда маленькие потери превращаются в большие победы.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдыхай с умом, тренируйся с силой.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Пусть каждый день отдыха наполняет тебя новой энергией.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это не остановка, это подготовка к прыжку вперед.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это твоя возможность заново влюбиться в тренировки.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Не забывай давать себе время на восстановление. Это важно.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Твое тело – твой храм. Ухаживай за ним с любовью и заботой.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Восстановление – это твой секретный ингредиент к успеху.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Пусть твой отдых будет так же активен, как и твои тренировки.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Величайшие победы начинаются с хорошего отдыха.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это время, когда мечты воплощаются в жизнь.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Пусть каждый отдых приносит тебе радость и вдохновение.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Отдых – это не конец тренировки, это начало новых возможностей.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Помни, что отдых – это тоже часть твоего тренировочного плана.",
            rest=True,
        ),
        MotivationalPhrase(
            text="Восстановление – это твой путь к более сильной версии себя.",
            rest=True,
        ),
    )
    MotivationalPhrase.objects.bulk_create(phrases)


def remove_phrases(apps, schema_editor):
    """Удаление мотивационных фраз."""
    MotivationalPhrase = apps.get_model("running", "MotivationalPhrase")
    MotivationalPhrase.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0003_delete_recreationphrase_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_phrases,
            reverse_code=remove_phrases
        )
    ]
