# Generated by Django 5.0.3 on 2024-03-14 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0004_add_data_motivationalphrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('training_end',), 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.RemoveField(
            model_name='history',
            name='training_date',
        ),
        migrations.AddField(
            model_name='history',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_comment='Города, в которых были совершены тренировки.', help_text='Города, в которых были совершены тренировки.', max_length=150, verbose_name='Города'), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(db_comment='Изображение пройденного маршрута на карте.', default=None, help_text='Изображение пройденного маршрута на карте.', upload_to='history_images/', verbose_name='Изображение маршрута'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='training_end',
            field=models.DateTimeField(db_comment='Дата и время окончания тренировки.', default=None, help_text='Дата и время окончания тренировки.', verbose_name='Время окончания тренировки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='training_start',
            field=models.DateTimeField(db_comment='Дата и время начала тренировки.', default=None, help_text='Дата и время начала тренировки.', verbose_name='Время начала тренировки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='avg_speed',
            field=models.FloatField(db_comment='Средняя скорость за всю тренировку.', help_text='Средняя скорость за всю тренировку.', verbose_name='Средняя скорость'),
        ),
        migrations.AlterField(
            model_name='history',
            name='distance',
            field=models.FloatField(db_comment='Пройденная дистанция в метрах.', help_text='Пройденная дистанция в метрах.', verbose_name='Дистанция (в метрах)'),
        ),
        migrations.AlterField(
            model_name='history',
            name='max_speed',
            field=models.FloatField(db_comment='Максимальная достигнутая скорость во время тренировки.', help_text='Максимальная достигнутая скорость во время тренировки.', verbose_name='Максимальная скорость'),
        ),
    ]
