# Generated by Django 5.0.3 on 2024-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0005_alter_history_options_remove_history_training_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, db_comment='Изображение пройденного маршрута на карте.', help_text='Изображение пройденного маршрута на карте.', null=True, upload_to='history_images/', verbose_name='Изображение маршрута'),
        ),
        migrations.AlterField(
            model_name='history',
            name='route',
            field=models.JSONField(blank=True, db_comment='Маршрут тренировки.', help_text='Маршрут тренировки.', null=True, verbose_name='Маршрут'),
        ),
    ]
