# Generated by Django 5.0.3 on 2024-03-19 17:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0006_alter_history_image_alter_history_route'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'verbose_name': 'День тренировки', 'verbose_name_plural': 'Дни тренировки'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ('training_end',), 'verbose_name': 'История тренировки', 'verbose_name_plural': 'История тренировок'},
        ),
        migrations.AddField(
            model_name='history',
            name='height_difference',
            field=models.PositiveSmallIntegerField(db_comment='Перепад высот.', default=1, help_text='Перепад высот.', verbose_name='Перепад высот'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), db_comment='Города, в которых были совершены тренировки.', help_text='Города, в которых были совершены тренировки.', size=None, verbose_name='Города'),
        ),
        migrations.AlterField(
            model_name='day',
            name='workout_info',
            field=models.CharField(db_comment='Описание тренировки дополнительно к этапам', help_text='Описание тренировки.', max_length=200, verbose_name='Описание тренировки'),
        ),
    ]
