# Generated by Django 5.0.3 on 2024-03-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0008_add_workout_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='black_white_icon',
            field=models.ImageField(db_comment='ЧБ иконка достижения.', default=1, help_text='ЧБ иконка, представляющая достижение.', upload_to='achievement_icons/', verbose_name='ЧБ иконка достижения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.ImageField(db_comment='Иконка достижения.', help_text='Иконка, представляющая достижение.', upload_to='achievement_icons/', verbose_name='Иконка достижения'),
        ),
    ]
