# Generated by Django 5.0.3 on 2024-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0009_achievement_black_white_icon_alter_achievement_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='stars',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
