# Generated by Django 5.0.3 on 2024-03-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0010_remove_achievement_stars_alter_achievement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='black_white_icon',
        ),
        migrations.RemoveField(
            model_name='history',
            name='completed',
        ),
    ]
