openapi: 3.0.3
info:
  title: API сервиса 100 дней бега
  version: 1.0.0
  description: Live докумениация сервиса
paths:
  /api/v1/achievements/:
    get:
      operationId: achievements_list
      description: Выводит список достижений
      summary: Список достижений
      tags:
      - Run
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Achievement'
          description: ''
  /api/v1/health/:
    get:
      operationId: health_retrieve
      description: Проверка работы АПИ
      summary: Проверка работы
      tags:
      - System
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                Health: OK
          description: ''
  /api/v1/history/:
    get:
      operationId: api_v1_history_list
      description: Выводит историю тренировок
      summary: История тренировок
      tags:
      - Run
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/History'
          description: ''
    post:
      operationId: api_v1_history_create
      description: Сохраняет выполненную тренировку
      summary: Сохранение выполненной тренировки
      tags:
      - Run
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/History'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/History'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/History'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AchievementEndTraining'
          description: ''
  /api/v1/me/:
    get:
      operationId: me_retrieve
      tags:
      - me
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: me_partial_update
      tags:
      - me
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: me_destroy
      tags:
      - me
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/resend_code/:
    post:
      operationId: resend_code_create
      tags:
      - resend_code
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/token/refresh/:
    post:
      operationId: token_refresh_create
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTokenObtain'
          description: ''
  /api/v1/training/:
    get:
      operationId: training_list
      description: Выводит список тренировок
      summary: Список тренировок
      tags:
      - Run
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Training'
          description: ''
  /api/v1/user/:
    post:
      operationId: user_create
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    Achievement:
      type: object
      description: Сериализатор достижения.
      properties:
        icon:
          type: string
          format: uri
          title: Иконка достижения
          description: Иконка, представляющая достижение.
        title:
          type: string
          title: Название достижения
          description: Название достижения.
          maxLength: 100
        description:
          type: string
          title: Описание достижения
          description: Описание достижения.
        reward_points:
          type: integer
          maximum: 32767
          minimum: 0
          title: Заморозка
          description: Количество заморозок за достижение.
        achievement_date:
          type: string
          format: date-time
        received:
          type: boolean
      required:
      - achievement_date
      - description
      - icon
      - received
      - title
    AchievementEndTraining:
      type: object
      description: Сериализатор достижения конца тренировки.
      properties:
        icon:
          type: string
          format: uri
        title:
          type: string
          title: Название достижения
          description: Название достижения.
          maxLength: 100
      required:
      - icon
      - title
    BlankEnum:
      enum:
      - ''
    CustomTokenObtain:
      type: object
      properties:
        email:
          type: string
          format: email
          writeOnly: true
        code:
          type: string
          writeOnly: true
          maxLength: 4
          minLength: 4
      required:
      - code
      - email
    GenderEnum:
      enum:
      - M
      - F
      type: string
      description: |-
        * `M` - Male
        * `F` - Female
    History:
      type: object
      description: Сериализатор историй тренировок.
      properties:
        training_start:
          type: string
          format: date-time
          writeOnly: true
          title: Время начала тренировки
          description: Дата и время начала тренировки.
        training_end:
          type: string
          format: date-time
          title: Время окончания тренировки
          description: Дата и время окончания тренировки.
        completed:
          type: boolean
          writeOnly: true
          title: Завершено
          description: Показывает, завершена ли тренировка или нет.
        training_day:
          type: integer
          maximum: 32767
          minimum: 0
          title: День тренировки
          description: День тренировки.
          writeOnly: true
        image:
          type: string
          format: uri
        motivation_phrase:
          type: string
          title: Мотивационная фраза
          description: Мотивационная фраза
          maxLength: 150
        cities:
          type: array
          items:
            type: string
            maxLength: 150
          writeOnly: true
          title: Города
          description: Города, в которых были совершены тренировки.
        route:
          nullable: true
          title: Маршрут
          description: Маршрут тренировки.
        distance:
          type: number
          format: double
          minimum: 0
          title: Дистанция (в метрах)
          description: Пройденная дистанция в метрах.
        time:
          type: integer
          description: Отдаёт продолжительность тренировки.
          readOnly: true
        max_speed:
          type: number
          format: double
          minimum: 0
          writeOnly: true
          title: Максимальная скорость
          description: Максимальная достигнутая скорость во время тренировки.
        avg_speed:
          type: number
          format: double
          minimum: 0
          title: Средняя скорость
          description: Средняя скорость за всю тренировку.
        achievements:
          type: array
          items:
            type: string
          writeOnly: true
      required:
      - avg_speed
      - cities
      - distance
      - max_speed
      - motivation_phrase
      - time
      - training_day
      - training_end
      - training_start
    PatchedUser:
      type: object
      description: Сериализатор кастомного пользователя.
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        gender:
          oneOf:
          - $ref: '#/components/schemas/GenderEnum'
          - $ref: '#/components/schemas/BlankEnum'
        height_cm:
          type: integer
          nullable: true
        weight_kg:
          type: number
          format: double
          nullable: true
        last_completed_training_number:
          type: integer
          readOnly: true
        amount_of_skips:
          type: integer
          readOnly: true
        avatar:
          type: string
          format: uri
    Training:
      type: object
      description: Сериализатор тренировок.
      properties:
        day_number:
          type: integer
          maximum: 32767
          minimum: 0
          title: Номер дня
          description: Номер дня.
        workout:
          title: Этапы тренировки
          description: Описанные этапы тренировки в json.
        workout_info:
          type: string
          title: Описание тренировки
          description: Описание тренировки.
          maxLength: 100
        motivation_phrase:
          type: string
        completed:
          type: boolean
      required:
      - day_number
      - motivation_phrase
      - workout
      - workout_info
    User:
      type: object
      description: Сериализатор кастомного пользователя.
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        gender:
          oneOf:
          - $ref: '#/components/schemas/GenderEnum'
          - $ref: '#/components/schemas/BlankEnum'
        height_cm:
          type: integer
          nullable: true
        weight_kg:
          type: number
          format: double
          nullable: true
        last_completed_training_number:
          type: integer
          readOnly: true
        amount_of_skips:
          type: integer
          readOnly: true
        avatar:
          type: string
          format: uri
      required:
      - amount_of_skips
      - email
      - last_completed_training_number
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
