openapi: 3.0.3
info:
  title: API сервиса 100 дней бега
  version: 1.0.0
  description: Live докумениация сервиса
paths:
  /api/v1/health/:
    get:
      operationId: health_retrieve
      description: Проверка работы АПИ
      summary: Проверка работы
      tags:
      - System
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                Health: OK
          description: ''
  /api/v1/me/:
    get:
      operationId: me_retrieve
      tags:
      - me
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
    patch:
      operationId: me_partial_update
      tags:
      - me
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCustomUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCustomUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCustomUser'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
    delete:
      operationId: me_destroy
      tags:
      - me
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/token/refresh/:
    post:
      operationId: token_refresh_create
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTokenObtain'
          description: ''
  /api/v1/user/:
    post:
      operationId: user_create
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomUser'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
components:
  schemas:
    CustomTokenObtain:
      type: object
      properties:
        email:
          type: string
          format: email
          writeOnly: true
        code:
          type: string
          writeOnly: true
          maxLength: 4
          minLength: 4
      required:
      - code
      - email
    CustomUser:
      type: object
      description: Serializer for the custom User model.
      properties:
        email:
          type: string
          format: email
        name:
          type: string
          title: Full name
          maxLength: 150
      required:
      - email
    PatchedCustomUser:
      type: object
      description: Serializer for the custom User model.
      properties:
        email:
          type: string
          format: email
        name:
          type: string
          title: Full name
          maxLength: 150
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
