openapi: 3.0.3
info:
  title: API сервиса 100 дней бега
  version: 1.0.0
  description: Live докумениация сервиса
paths:
  /api/v1/v1/health/:
    get:
      operationId: health_retrieve
      description: Проверка работы АПИ
      summary: Проверка работы
      tags:
      - System
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                Health: OK
          description: ''
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
