openapi: 3.0.3
info:
  title: API сервиса 100 дней бега
  version: 1.0.0
  description: Live докумениация сервиса
paths:
  /api/v1/health/:
    get:
      operationId: health_retrieve
      description: Проверка работы АПИ
      summary: Проверка работы
      tags:
      - System
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                Health: OK
          description: ''
  /api/v1/user/:
    post:
      operationId: user_create
      tags:
      - user
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
