# Generated by Django 5.0.2 on 2024-02-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_of_skips',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='last completed training'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_completed_training_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='last completed training'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=150, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
