# Generated by Django 5.0.2 on 2024-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Set')], default='M', max_length=2, verbose_name='gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='height in cm'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.FloatField(null=True, verbose_name='weight in kg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='amount_of_skips',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='amount of skips available'),
        ),
    ]
