# Generated by Django 5.0.2 on 2024-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender_user_height_cm_user_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='height in cm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='weight in kg'),
        ),
    ]
