# Generated by Django 5.0.3 on 2024-03-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_amount_of_skips_and_more'),
        ('users', '0003_alter_user_options_user_image_and_more'),
    ]

    operations = [
    ]
