# Generated by Django 5.0.2 on 2024-02-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_height_cm_alter_user_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Set')], default='NS', max_length=2, verbose_name='gender'),
        ),
    ]
