# Generated by Django 5.0.3 on 2024-03-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0009_achievement_black_white_icon_alter_achievement_icon'),
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_completed_training_number',
        ),
        migrations.AddField(
            model_name='user',
            name='date_last_skips',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего пропуска'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_completed_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='running.history', verbose_name='Последняя завершенная тренировка'),
        ),
    ]
