# Generated by Django 5.0.3 on 2024-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_last_completed_training_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_m_run',
            field=models.IntegerField(default=0, verbose_name='Всего пробежал метров'),
        ),
    ]
