# Generated by Django 5.0.3 on 2024-03-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_total_m_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Часовой пояс пользователя'),
        ),
    ]
