# Generated by Django 5.0.3 on 2024-04-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_m_run',
            field=models.FloatField(default=0, verbose_name='Всего пробежал метров'),
        ),
    ]
