# Generated by Django 5.0.4 on 2024-06-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_total_m_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_training',
            field=models.BooleanField(default=False, verbose_name='Блокировка тренировок'),
        ),
    ]
